
---
include:
 - docker-compose-traefik.yml
 - docker-compose-authentik.yml

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: flowcaseweb/flowcase
    container_name: flowcase-web
    restart: unless-stopped
    volumes:
      - flowcase-data:/flowcase/data
      - flowcase-nginx-data:/flowcase/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
    networks:
      - default_network
    command: python run.py --traefik-authentik # --registry-lock https://my-private-locked-registry.example

  nginx:
    image: nginx:1.28-alpine
    container_name: flowcase-nginx
    restart: unless-stopped
    volumes:
      - flowcase-nginx-data:/etc/nginx/conf.d
    depends_on:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.flowcase.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.flowcase.entrypoints=websecure
      - traefik.http.routers.flowcase.tls.certresolver=acme-resolver
      - traefik.http.services.flowcase.loadbalancer.server.port=80
      # enable middleware to add authentication by authentik
      - traefik.http.routers.flowcase.middlewares=authentik@file
      - traefik.docker.network=proxy_network
    networks:
      - default_network
      - proxy_network

networks:
  default_network:
    driver: bridge

volumes:
  flowcase-data:
    external: false
  flowcase-nginx-data:
    external: false